language: python
sudo: false
before_script:
- pip install tox

# test script
script:  tox
notifications:
  on_success: change
  on_failure: always

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 2.7
    env: TOXENV=py27 REQUESTS_VERSION="===2.2.1"
  - python: 2.7
    env: TOXENV=py27 REQUESTS_VERSION="===2.1.0"
  - python: 3.4
    env: TOXENV=py34
  - python: 3.4
    env: TOXENV=py34 REQUESTS_VERSION="===2.2.1"
  - python: 3.4
    env: TOXENV=py34 REQUESTS_VERSION="===2.1.0"
  - python: 3.5
    env: TOXENV=py35
  - python: 3.5
    env: TOXENV=py35 REQUESTS_VERSION="===2.2.1"
  - python: 3.5
    env: TOXENV=py35 REQUESTS_VERSION="===2.1.0"
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6
    env: TOXENV=py36 REQUESTS_VERSION="===2.2.1"
  - python: 3.6
    env: TOXENV=py36 REQUESTS_VERSION="===2.1.0"
  - python: nightly
    env: TOXENV=py37
  - python: nightly
    env: TOXENV=py37 REQUESTS_VERSION="===2.2.1"
  - python: nightly
    env: TOXENV=py37 REQUESTS_VERSION="===2.1.0"
  - python: 3.6
    env: TOXENV=noopenssl
  - env: TOXENV=py27-flake8
  - env: TOXENV=py34-flake8
  - env: TOXENV=docstrings
  - env: TOXENV=docs
  - env: TOXENV=readme
  allow_failures:
  - env: TOXENV=docstrings
